apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: env
version: 0.1.0
dependencies:
  - name: aws-alb-ingress-controller
    version: 1.0.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    alias: alb
  - name: external-dns
    version: 3.2.1
    repository: https://charts.bitnami.com/bitnami
    alias: externaldns
  - name: nginx-ingress  
    version: 1.40.1
    repository: http://storage.googleapis.com/kubernetes-charts
    alias: nginx
