dependencies:
- name: aws-alb-ingress-controller
  version: 1.0.0
  repository: http://storage.googleapis.com/kubernetes-charts-incubator
  alias: alb
- name: external-dns
  version: 2.20.4
  repository: http://storage.googleapis.com/kubernetes-charts
  alias: externaldns
- name: nginx-ingress  
  version: 1.40.1
  repository: http://storage.googleapis.com/kubernetes-charts
  alias: nginx

    